config/routes.rb
Rails.application.routes.draw do
 


  get 'communities', to: 'communities#index'

  get 'communities/new', to: 'communities#new'
  post 'communities', to: 'communities#create'

  get 'communities/:id', to: 'communities#show', as: 'community_show'

  get 'communities/update'

  resources :community_tag_lists
  resources :event_category_lists
  
  # scope 'events', as: 'events' do
  #   root 'events#index'
  # end


  # get 'events/new', to: 'events#new'
  # get 'events/:id', to: 'events#show'
  # get 'events/:id/edit', to: 'events#edit'
  # # ,as: :edit_events
  # post 'events', to: 'events#create'
  # post 'events/:id/edit', to: 'events#update'
  

  resources :events, except: [ :destroy ] do
    member do
      get :fix, to: 'events#fix'
      patch :fix, to: 'events#fixed', as: 'fixed'
      get :participate, to: 'events#participate', as: 'participate'
    end
    collection do
    end
  end

  resource :event_users, only: [ :create, :update ]

  resources :event_messages, only: [ :create, :update ]

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users



  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/chat_room/:id', to: 'chat_rooms#show'
end

app/models/community_tag_list.rb
class CommunityTagList < ApplicationRecord
  # has_many :community_tags
end

app/controllers/community_tag_lists_controller.rb
class CommunityTagListsController < ApplicationController
  before_action :set_community_tag_list, only: [:show, :edit, :update, :destroy]

  # GET /community_tag_lists
  # GET /community_tag_lists.json
  def index
    @community_tag_lists = CommunityTagList.all
  end

  # GET /community_tag_lists/1
  # GET /community_tag_lists/1.json
  def show
  end

  # GET /community_tag_lists/new
  def new
    @community_tag_list = CommunityTagList.new
  end

  # GET /community_tag_lists/1/edit
  def edit
  end

  # POST /community_tag_lists
  # POST /community_tag_lists.json
  def create
    @community_tag_list = CommunityTagList.new(community_tag_list_params)

    respond_to do |format|
      if @community_tag_list.save
        format.html { redirect_to @community_tag_list, notice: 'Community tag list was successfully created.' }
        format.json { render :show, status: :created, location: @community_tag_list }
      else
        format.html { render :new }
        format.json { render json: @community_tag_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /community_tag_lists/1
  # PATCH/PUT /community_tag_lists/1.json
  def update
    respond_to do |format|
      if @community_tag_list.update(community_tag_list_params)
        format.html { redirect_to @community_tag_list, notice: 'Community tag list was successfully updated.' }
        format.json { render :show, status: :ok, location: @community_tag_list }
      else
        format.html { render :edit }
        format.json { render json: @community_tag_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /community_tag_lists/1
  # DELETE /community_tag_lists/1.json
  def destroy
    @community_tag_list.destroy
    respond_to do |format|
      format.html { redirect_to community_tag_lists_url, notice: 'Community tag list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community_tag_list
      @community_tag_list = CommunityTagList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_tag_list_params
      params.require(:community_tag_list).permit(:tag_name)
    end
end

app/helpers/community_tag_lists_helper.rb
module CommunityTagListsHelper
end

app/views/community_tag_lists/_form.html.erb
<%= form_with(model: community_tag_list, local: true) do |form| %>
  <% if community_tag_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(community_tag_list.errors.count, "error") %> prohibited this community_tag_list from being saved:</h2>

      <ul>
      <% community_tag_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tag_name %>
    <%= form.text_field :tag_name, id: :community_tag_list_tag_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/community_tag_lists/edit.html.erb
<h1>Editing Community Tag List</h1>

<%= render 'form', community_tag_list: @community_tag_list %>

<%= link_to 'Show', @community_tag_list %> |
<%= link_to 'Back', community_tag_lists_path %>

app/views/community_tag_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Community Tag Lists</h1>

<table>
  <thead>
    <tr>
      <th>Tag name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @community_tag_lists.each do |community_tag_list| %>
      <tr>
        <td><%= community_tag_list.tag_name %></td>
        <td><%= link_to 'Show', community_tag_list %></td>
        <td><%= link_to 'Edit', edit_community_tag_list_path(community_tag_list) %></td>
        <td><%= link_to 'Destroy', community_tag_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Community Tag List', new_community_tag_list_path %>

app/views/community_tag_lists/new.html.erb
<h1>New Community Tag List</h1>

<%= render 'form', community_tag_list: @community_tag_list %>

<%= link_to 'Back', community_tag_lists_path %>

app/views/community_tag_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag name:</strong>
  <%= @community_tag_list.tag_name %>
</p>

<%= link_to 'Edit', edit_community_tag_list_path(@community_tag_list) %> |
<%= link_to 'Back', community_tag_lists_path %>