config/routes.rb
Rails.application.routes.draw do
 


  get 'communities', to: 'communities#index'

  get 'communities/new', to: 'communities#new'
  post 'communities', to: 'communities#create'

  get 'communities/:id', to: 'communities#show', as: 'community_show'

  get 'communities/update'

  resources :community_tag_lists
  resources :event_category_lists
  
  # scope 'events', as: 'events' do
  #   root 'events#index'
  # end


  # get 'events/new', to: 'events#new'
  # get 'events/:id', to: 'events#show'
  # get 'events/:id/edit', to: 'events#edit'
  # # ,as: :edit_events
  # post 'events', to: 'events#create'
  # post 'events/:id/edit', to: 'events#update'
  

  resources :events, except: [ :destroy ] do
    member do
      get :fix, to: 'events#fix'
      patch :fix, to: 'events#fixed', as: 'fixed'
      get :participate, to: 'events#participate', as: 'participate'
    end
    collection do
    end
  end

  resource :event_users, only: [ :create, :update ]

  resources :event_messages, only: [ :create, :update ]

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users



  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/chat_room/:id', to: 'chat_rooms#show'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :event_category_list
  belongs_to :user
  validates :event_name, presence: true, length: { maximum: 20 }
  validates :user_id, presence: true, numericality: { only_integer: true } 
  validates :event_category_list_id , presence: true, length: { maximum: 8 }
  validates :event_detail, presence: true, length: { maximum: 100 }
  validates :event_flag, length: { maximum: 8 }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :fix, :fixed]

  def show
    @event_flag = EventUser.where(user_id: current_user).where(event_id: @event.id)
    @event_message = EventMessage.new

    if @event_flag.empty?
      @event_user = EventUser.new
    else
      @event_user = @event_flag[0]
    end

    @participants = EventUser.where(event_id: @event.id).where(schedule_flag: 1)
    @event_messages = EventMessage.where(event_id: @event.id)
  end

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    @event_category_lists = EventCategoryList.all
  end

  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to "/events/#{@event.id}", notice: 'イベントの作成に成功しました' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { redirect_to "/events/new" }
        format.json { render json: @event_errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @event_category_lists = EventCategoryList.all
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'イベントのアップデートに成功しました' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    
  end

  def fix
    @event = Event.find(params[:id])
  end

  def fixed
    respond_to do |format|
      if @event.update(event_fix_params)
        format.html { redirect_to @event, notice: 'イベントのフラグを変更しました' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :fix,notice:'失敗した' }
        format.json { render json: @event, status: :unprocessable_entity }
      end
    end
  end

  # def participate
    
  # end



private 

  def set_event
    @event = Event.find(params[:id])
  end


  def event_params
    params.require(:event).permit(:event_name, :event_category_list_id, :event_detail, :user_id)
  end

  def event_fix_params
    params.require(:event).permit(:event_flag)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= f.label :event_name %><%= f.text_field :event_name %><br>
  <p>イベントのカテゴリーを選んでください</p>
  <%= f.collection_radio_buttons(:event_category_list_id, @event_category_lists, :id, :event_category_name) do |b| %>
    <%= b.label {b.radio_button + b.text} %>
  <% end %>
  <%= f.label "イベントの詳細を入力してね" %><%= f.text_area :event_detail %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<%= render 'form' %>

app/views/events/fix.html.erb
<%=flash[:notice];%>


<%= form_for(@event, url: fixed_event_path) do |f| %>
  <p>イベント：<%= @event.event_name %> はもう終わりましたか？</p>
  <label><%= f.radio_button :event_flag, 1 %>無事に完了した</label>
  <label><%= f.radio_button :event_flag, 2 %>中止になった</label>
  <%= f.submit '送信', data: { confirm: '保存してもいいですか？',
   disable_with: '処理中...' } %>
<% end %>

app/views/events/index.html.erb
<h1>Events#index</h1>


<table>
  <tr>
    <th>ID</th>
    <th>イベント名</th>
    <th>カテゴリーID</th>
    <th>イベント詳細</th>
    <th>イベントフラグ</th>
    <th>このイベントを確認する</th>
    <th>edit</th>
  </tr>

  <% @events.each do |event| %>
  <tr>
    <td><%= event.id %></td>
    <td><%= event.event_name %></td>
    <td><%= event.event_category_list.event_category_name %></td>
    <td><%= event.event_detail %></td>
    <td><%= event.event_flag %></td>
    <td><%= link_to 'イベントページへ', event_path(event) %></td>
    <td><a href="/events/<%= event.id %>/edit">編集する</a></td>
    <td><a href="/events/<%= event.id %>/fix">FIX!</a></td>
  </tr>
  <% end %>
</table>

<a href="/events/new">新しいイベントを作る</a>

app/views/events/new.html.erb
<h1>新規イベント作成</h1>
<%= render 'form' %>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p><%= flash[:notice] %></p>
<p><%= flash[:success] %></p>

<p><%= @event.id %></p>
<p><%= @event.event_name %></p>
<p><%= @event.event_category_list.event_category_name %></p>
<p><%= @event.event_detail %></p>
<p><%= @event.event_flag %></p>
<p>このイベントの管理者: <%= @event.user.name %></p>


<% if @event_flag.nil? %>
  <%= form_for(@event_user, url: { controller: 'event_users', action: 'create' }) do |f| %>
    <p>このイベントに参加しますか？</p>
    <label><%= f.radio_button :schedule_flag, 1 %>参加する</label>
    <label><%= f.radio_button :schedule_flag, 2 %>参加しない</label>
    <label><%= f.radio_button :schedule_flag, 3 %>未定</label>
    
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :event_id, :value => @event.id %>
    <%= f.submit %>
  <% end %>

<% else %>
  <%= form_for(@event_user, url: { controller: 'event_users', action: 'update' }) do |f| %>
    <p>このイベントへ参加しますか？</p>
    <label><%= f.radio_button :schedule_flag, 1 %>参加する</label>
    <label><%= f.radio_button :schedule_flag, 2 %>参加しない</label>
    <label><%= f.radio_button :schedule_flag, 3 %>未定</label>
    
    <%= f.hidden_field :id, value: @event_user.id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :event_id, :value => @event.id %>
    <%= f.submit  %>
  <% end %>
  
<% end %>

<p>このイベントに参加する人</p>
<% @participants.each do |participant| %>
  <p><%= participant.user.name %>さん</p>
<% end %>

<%= form_for(@event_message) do |f| %>
  <p>このイベントにメッセージを送信する</p>
  <label><%= f.text_field :content %></label>
  
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :event_id, value: @event.id %>
  <%= f.submit %>
<% end %>


<p>このイベントへのメッセージ一覧</p>
<% @event_messages.each do |event_message| %>
  <p><span><%= event_message.user.name %>さん: </span><%= event_message.content %></p>
<% end %>


<%= form_for(@event_message) do |f| %>
  <p>このイベントにメッセージを送信する</p>
  <label><%= f.text_field :content %></label>
  
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :event_id, value: @event.id %>
  <%= f.submit %>
<% end %>