config/routes.rb
Rails.application.routes.draw do
 


  get 'communities', to: 'communities#index'

  get 'communities/new', to: 'communities#new'
  post 'communities', to: 'communities#create'

  get 'communities/:id', to: 'communities#show', as: 'community_show'

  get 'communities/update'

  resources :community_tag_lists
  resources :event_category_lists
  
  # scope 'events', as: 'events' do
  #   root 'events#index'
  # end


  # get 'events/new', to: 'events#new'
  # get 'events/:id', to: 'events#show'
  # get 'events/:id/edit', to: 'events#edit'
  # # ,as: :edit_events
  # post 'events', to: 'events#create'
  # post 'events/:id/edit', to: 'events#update'
  

  resources :events, except: [ :destroy ] do
    member do
      get :fix, to: 'events#fix'
      patch :fix, to: 'events#fixed', as: 'fixed'
      get :participate, to: 'events#participate', as: 'participate'
    end
    collection do
    end
  end

  resource :event_users, only: [ :create, :update ]

  resources :event_messages, only: [ :create, :update ]

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users



  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/chat_room/:id', to: 'chat_rooms#show'
end

app/models/event_category_list.rb
class EventCategoryList < ApplicationRecord
  has_many :events
end

app/controllers/event_category_lists_controller.rb
class EventCategoryListsController < ApplicationController
  before_action :set_event_category_list, only: [:show, :edit, :update, :destroy]

  # GET /event_category_lists
  # GET /event_category_lists.json
  def index
    @event_category_lists = EventCategoryList.all
  end

  # GET /event_category_lists/1
  # GET /event_category_lists/1.json
  def show
  end

  # GET /event_category_lists/new
  def new
    @event_category_list = EventCategoryList.new
  end

  # GET /event_category_lists/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /event_category_lists
  # POST /event_category_lists.json
  def create
    @event_category_list = EventCategoryList.new(event_category_list_params)

    respond_to do |format|
      if @event_category_list.save
        format.html { redirect_to @event_category_list, notice: 'Event category list was successfully created.' }
        format.json { render :show, status: :created, location: @event_category_list }
      else
        format.html { render :new }
        format.json { render json: @event_category_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_category_lists/1
  # PATCH/PUT /event_category_lists/1.json
  def update
    respond_to do |format|
      if @event_category_list.update(event_category_list_params)
        format.html { redirect_to @event_category_list, notice: 'Event category list was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_category_list }
      else
        format.html { render :edit }
        format.json { render json: @event_category_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_category_lists/1
  # DELETE /event_category_lists/1.json

  # デリートはしない！！！
  # def destroy
  #   @event_category_list.destroy
  #   respond_to do |format|
  #     format.html { redirect_to event_category_lists_url, notice: 'Event category list was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_category_list
      @event_category_list = EventCategoryList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_category_list_params
      params.require(:event_category_list).permit(:event_category_name)
    end
end

app/helpers/event_category_lists_helper.rb
module EventCategoryListsHelper
end

app/views/event_category_lists/_form.html.erb
<%= form_with(model: event_category_list, local: true) do |form| %>
  <% if event_category_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_category_list.errors.count, "error") %> prohibited this event_category_list from being saved:</h2>

      <ul>
      <% event_category_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "イベントカテゴリー名" %>
    <%= form.text_field :event_category_name, id: :event_category_list_event_category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_category_lists/edit.html.erb
<h1>Editing Event Category List</h1>

<%= render 'form', event_category_list: @event_category_list %>

<%= link_to 'Show', @event_category_list %> |
<%= link_to 'Back', event_category_lists_path %>

app/views/event_category_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Category Lists</h1>

<table>
  <thead>
    <tr>
      <th>イベントカテゴリーID</th>
      <th>イベントカテゴリー名</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_category_lists.each do |event_category_list| %>
      <tr>
        <td><%= event_category_list.id %></td>
        <td><%= event_category_list.event_category_name %></td>
        <td><%= link_to 'Show', event_category_list %></td>
        <td><%= link_to 'Edit', edit_event_category_list_path(event_category_list) %></td>
         <%# 
         <td><%= link_to 'Destroy', event_category_list, method: :delete, data: { confirm: 'Are you sure?' } %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しいイベントを作る', new_event_category_list_path %>

app/views/event_category_lists/new.html.erb
<h1>新しいイベント</h1>

<%= render 'form', event_category_list: @event_category_list %>

<%= link_to 'Back', event_category_lists_path %>

app/views/event_category_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>イベント名:</strong>
  <%= @event_category_list.event_category_name %>
</p>

<%= link_to 'Edit', edit_event_category_list_path(@event_category_list) %> |
<%= link_to 'Back', event_category_lists_path %>